name: "CD"

on:
  workflow_run:
    workflows: ["Deploy to EC2"]
    types:
      - completed

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: "Setup Python"
              uses: actions/setup-python@v2
              with:
                python-version: '3.x'
            - name: "Download Artifact"
              uses: actions/download-artifact@v4
              with:
                  name: fastapiserver
                  run_id: ${{ github.event.workflow_run.id }}
                  github_token: ${{ github.token }}
            - name: "Echo Data"
              run: |
                    echo "Artifact downloaded"
                    ls