name: "Hello World Job"

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Setup Python"
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: "Echo"
        run: |
          echo "Hello World"
          