name: "Conditional Formatting"

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main
    workflow_dispatch:
jobs:
    on-push:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: "Step1"
              run: echo "This is Step 1"

    on-pr:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: "Step2"
              run: echo "This is Step 2"
    on-dispath:
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps:
            - name: "Step3"
              run: echo "This is Step 3"